In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam'] = df['Category'].apply(lambda x:1 if x == 'spam' else 0)

In [6]:
df.shape

(5572, 3)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

**Train Test Split**

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [11]:
X_train.shape

(4457,)

In [12]:
X_test.shape

(1115,)

In [13]:
type(X_train)

pandas.core.series.Series

In [14]:
X_train[:4]

918     When people see my msgs, They think Iam addict...
350     Just checking in on you. Really do miss seeing...
1228           So ü'll be submitting da project tmr rite?
2000        LMAO where's your fish memory when I need it?
Name: Message, dtype: object

In [15]:
type(y_train)

pandas.core.series.Series

In [16]:
y_train[:4]

918     0
350     0
1228    0
2000    0
Name: spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

**Create bag of words representation using CountVectorizer**

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7752 sparse matrix of type '<class 'numpy.int64'>'
	with 59230 stored elements in Compressed Sparse Row format>

In [19]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
X_train_cv.shape

(4457, 7752)

In [21]:
v.get_feature_names_out()[1771]

'chat'

In [22]:
v.vocabulary_

{'when': 7493,
 'people': 5145,
 'see': 5987,
 'my': 4667,
 'msgs': 4625,
 'they': 6849,
 'think': 6856,
 'iam': 3594,
 'addicted': 832,
 'to': 6943,
 'msging': 4621,
 'are': 1075,
 'wrong': 7640,
 'bcoz': 1292,
 'don': 2426,
 'know': 3965,
 'that': 6822,
 'sweet': 6663,
 'friends': 3031,
 'bslvyl': 1562,
 'just': 3883,
 'checking': 1785,
 'in': 3654,
 'on': 4931,
 'you': 7715,
 'really': 5609,
 'do': 2397,
 'miss': 4507,
 'seeing': 5989,
 'jeremiah': 3822,
 'have': 3376,
 'great': 3259,
 'month': 4578,
 'so': 6291,
 'll': 4159,
 'be': 1298,
 'submitting': 6567,
 'da': 2161,
 'project': 5451,
 'tmr': 6937,
 'rite': 5803,
 'lmao': 4162,
 'where': 7497,
 'your': 7720,
 'fish': 2895,
 'memory': 4444,
 'need': 4727,
 'it': 3771,
 'stop': 6503,
 'calling': 1647,
 'everyone': 2687,
 'saying': 5935,
 'might': 4473,
 'cancer': 1665,
 'throat': 6884,
 'hurts': 3582,
 'talk': 6707,
 'can': 1658,
 'answering': 1010,
 'everyones': 2688,
 'calls': 1649,
 'if': 3620,
 'get': 3145,
 'one': 4936,
 'mo

In [23]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
np.where(X_train_np[0]!=0)

(array([ 832, 1075, 1292, 1562, 2426, 3031, 3594, 3965, 4621, 4625, 4667,
        5145, 5987, 6663, 6822, 6849, 6856, 6943, 7493, 7640], dtype=int64),)